name: Bug Report
description: File a bug report.
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before filing a bug report, please make sure to look at open issues in order to not open a duplicate of anothe one.
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what your bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: What did you do to get around the problem?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Optionally add your Player.log from %USERPROFILE%\AppData\LocalLow\Intercept Games\Kerbal Space Program 2. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here. You can also upload screenshots.
    validations:
      required: false
